### ISSUE TITLE
Error in Get comments and Get count 

### ISSUE THREAD

**Issue by kushipabo** [LayuruLK/ElectS---Advanced-E-Voting-System#82]
![Screenshot (146)](https://github.com/user-attachments/assets/d638a408-2362-4c7c-a0ae-1144c14517ba)
![Screenshot (147)](https://github.com/user-attachments/assets/5e9063bb-2138-4933-80d4-17074c2a0422)

**Comment by Kasunchira** [comment]
issue solved
